language: c
compiler:
  - gcc
  - clang
services:
  - memcached
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf iproute-dev
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-netlink/.travis_build_config.rb build_config.rb
script: 
  - make all test
notifications:
  webhooks:
    - secure: "g0zD0o2XdyOzScnOZgO4di1Ebbw4d/mS/Ws77a0lLWiU2+8RyMq2Py9be0KYTiHk85uvdPjidBaDl/d+I7I6gXrjCALwaMlKzE7CtaM9KnyM1xYctFBUdCmYE+QN7DTs4C+d0T6XsCgqAoATscInT+a/zS6sKcHge5hrNwPny3s="

